"""
prospect-radar — single-prospect runner.

Given a prospect name (existing in the universe or new), this script runs the
full signal-harvest → score → PVP pipeline as one Claude orchestration with
tool use, and writes a brief to output/briefs/<slug>.md.

Usage:
    python run.py --prospect "Acme Corp"
    python run.py --prospect "Acme Corp" --refresh
    python run.py --prospect "New Co" --add-to-universe

The weekly top-10 brief is generated by prompts/run.md from inside Claude Code.
This script exists for ad-hoc one-off prospect scoring (e.g. an inbound lead
that needs to be qualified before a meeting).

Requires:
    pip install anthropic pyyaml
    export ANTHROPIC_API_KEY=...
"""

import argparse
import os
import re
import sys
from datetime import date
from pathlib import Path

import anthropic
import yaml

# ---------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).parent
TARGET_CONFIG_PATH = PROJECT_ROOT / "config" / "target.yaml"
UNIVERSE_PATH = PROJECT_ROOT / "data" / "universe.yaml"
SCORING_PATH = PROJECT_ROOT / "scoring" / "rubric.md"
PVP_AGENT_PATH = PROJECT_ROOT / "agents" / "pvp-generator.md"
OUTPUT_DIR = PROJECT_ROOT / "output" / "briefs"

# Sonnet 4.6 is fast enough for single-prospect runs. Opus only matters for
# the weekly run where the entire universe is re-scored.
MODEL = "claude-sonnet-4-6"


# ---------------------------------------------------------------------
# Config + universe handling
# ---------------------------------------------------------------------

def load_yaml(path: Path):
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found. "
            f"Copy from {path.with_suffix('.example' + path.suffix)} and edit."
        )
    with path.open() as f:
        return yaml.safe_load(f)


def load_universe() -> list[dict]:
    return load_yaml(UNIVERSE_PATH) or []


def load_target() -> dict:
    return load_yaml(TARGET_CONFIG_PATH) or {}


def find_prospect(universe: list[dict], name: str) -> dict | None:
    """Case-insensitive substring match on prospect name."""
    needle = name.lower()
    for p in universe:
        if "name" not in p:
            continue
        if needle in p["name"].lower():
            return p
    return None


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


# ---------------------------------------------------------------------
# Claude orchestration
# ---------------------------------------------------------------------

SYSTEM_PROMPT_PREFIX = """You are prospect-radar — a multi-agent intelligence \
system for a B2B SaaS sales team. Your job is to evaluate one prospect and \
produce a usable account brief.

You think like a senior B2B SaaS account executive. You score prospects on \
Pain × Timing × Fit. You write briefs that an AE can act on Monday morning, \
not decks. You cite sources for every non-trivial claim.

You have access to web search. Use it to harvest:
  - Recent news (M&A, funding, exec changes, expansion, incidents)
  - Job postings (build-vs-buy signals)
  - Customer-facing reviews (App Store, G2, Trustpilot — product-blamed pain)
  - LinkedIn posts from leadership (where indexed)

Output a markdown brief in the exact format described below.

The target company's product, ICP, pricing, proof points, and buyer personas \
are provided in the TARGET CONFIG section below. Use the proof_points block \
to match the right reference to the right prospect.
"""


def build_system_prompt() -> list[dict]:
    """Build the system prompt with cache breakpoints on the heavy bits.

    Prompt caching saves the target config + universe + scoring rubric +
    PVP agent spec across calls. These rarely change but are large.
    Anthropic's prompt cache survives 5 minutes by default, which is
    plenty for a single run.
    """
    target = TARGET_CONFIG_PATH.read_text()
    universe = UNIVERSE_PATH.read_text()
    scoring = SCORING_PATH.read_text()
    pvp_agent = PVP_AGENT_PATH.read_text()

    cached_block = {
        "type": "text",
        "text": (
            SYSTEM_PROMPT_PREFIX
            + "\n\n=== TARGET CONFIG ===\n"
            + target
            + "\n\n=== PROSPECT UNIVERSE ===\n"
            + universe
            + "\n\n=== SCORING RUBRIC ===\n"
            + scoring
            + "\n\n=== PVP AGENT SPEC ===\n"
            + pvp_agent
        ),
        "cache_control": {"type": "ephemeral"},
    }

    return [cached_block]


USER_TEMPLATE = """Prospect to evaluate: **{prospect_name}**

{prospect_context}

## Your task

1. Harvest signals across news, jobs, customer-facing reviews, and LinkedIn.
2. Score using the rubric in the system prompt: Pain × Timing × Fit.
3. Generate a Pain / Value / Proof brief using the PVP agent spec. Match the
   right proof point from the target config's proof_points block.
4. Pass the 3 WHYs audit on the draft message.
5. Output the full brief as markdown in the format below.

Use the web_search tool liberally. Cite URLs for every signal.

## Output format (Markdown)

```markdown
# {prospect_name} — Account brief

**prospect-radar score:** [X] (Pain [n] × Timing [n] × Fit [n])
**Recommended action:** [one line]
**Generated:** {today}

## Snapshot
[table: HQ, geography, size, segment, current vendor, pain signal]

## Why now
[the 1-3 timing signals that matter, with URLs]

## The pain dossier
[the public evidence of pain, with URLs]

## Specific fit
[your product's capability match, with proof point]

## Three-message sequence
[message 1: first touch to primary contact]
[message 2: follow-up at +7 days]
[message 3: to economic buyer if message 1 engages]

## Discovery questions
[5-7 questions for first call]

## Risks / disqualifiers
[what would kill this]

## Confidence
[High / Medium / Low + reasoning]

## Sources
[bulleted URLs]
```

Begin.
"""


def run_prospect_brief(prospect_name: str, universe: list[dict]) -> str:
    """Run Claude with web search to produce a brief for one prospect.

    Returns the markdown content.
    """
    existing = find_prospect(universe, prospect_name)

    if existing:
        prospect_context = (
            f"This prospect is in the tracked universe. Existing record:\n\n"
            f"```yaml\n{yaml.dump(existing)}\n```\n\n"
            f"Refresh the signal harvest. The static record may be stale."
        )
    else:
        prospect_context = (
            "This prospect is NOT yet in the tracked universe. "
            "Confirm they exist, classify their segment and size, "
            "and produce the brief from scratch."
        )

    client = anthropic.Anthropic()

    # Single-call orchestration. Claude handles tool use loops internally
    # when given the web_search tool.
    response = client.messages.create(
        model=MODEL,
        max_tokens=8192,
        system=build_system_prompt(),
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        messages=[
            {
                "role": "user",
                "content": USER_TEMPLATE.format(
                    prospect_name=prospect_name,
                    prospect_context=prospect_context,
                    today=date.today().isoformat(),
                ),
            }
        ],
    )

    # Extract final text. With tool use, the model may have several
    # message turns; the final assistant content block is what we want.
    text_blocks = [
        block.text
        for block in response.content
        if block.type == "text"
    ]
    return "\n\n".join(text_blocks)


# ---------------------------------------------------------------------
# Universe mutation
# ---------------------------------------------------------------------

def add_to_universe(prospect_name: str) -> None:
    """Append a stub record to universe.yaml for a new prospect.

    Conservative: extracts only what's confidently parseable. Anything
    ambiguous is left for the human to fill in.
    """
    stub = {
        "name": prospect_name,
        "current_platform": "Unknown",
        "platform_confidence": "Unknown",
        "status": "Active",
        "fit_score": 3,  # provisional, human should refine
        "added_by": "run.py",
        "added_date": date.today().isoformat(),
    }
    universe = load_universe()
    universe.append(stub)
    with UNIVERSE_PATH.open("w") as f:
        yaml.dump(universe, f, sort_keys=False)
    print(f"Stub appended for {prospect_name}. Refine fit_score manually.")


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="prospect-radar — single-prospect runner"
    )
    parser.add_argument("--prospect", required=True, help="Prospect name to brief")
    parser.add_argument(
        "--refresh",
        action="store_true",
        help="Force refresh even if brief exists",
    )
    parser.add_argument(
        "--add-to-universe",
        action="store_true",
        help="Append the prospect as a stub to universe.yaml",
    )
    args = parser.parse_args()

    # Pre-flight checks
    for path in (TARGET_CONFIG_PATH, UNIVERSE_PATH, SCORING_PATH):
        if not path.exists():
            sys.exit(
                f"Missing required file: {path}\n"
                f"Copy from the .example file and edit before running."
            )

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_path = OUTPUT_DIR / f"{slugify(args.prospect)}.md"

    if output_path.exists() and not args.refresh:
        print(
            f"Brief already exists at {output_path}. "
            f"Use --refresh to regenerate."
        )
        sys.exit(0)

    target = load_target()
    universe = load_universe()
    print(f"Target company: {target.get('company', {}).get('name', '(unset)')}")
    print(f"Universe loaded: {len(universe)} prospects tracked.")
    print(f"Running brief for: {args.prospect} (model: {MODEL})")
    print("This typically takes 60-120 seconds with web search...")

    brief = run_prospect_brief(args.prospect, universe)
    output_path.write_text(brief)
    print(f"\nBrief written: {output_path}")

    if args.add_to_universe:
        add_to_universe(args.prospect)


if __name__ == "__main__":
    main()
