"""
Wunder Radar — single-operator runner.

Given an operator name (existing in the universe or new), this script runs the
full signal-harvest → score → PVP pipeline as one Claude orchestration with
tool use, and writes a brief to output/briefs/<slug>.md.

Usage:
    python run.py --operator "Free Now Drive"
    python run.py --operator "Nextbike" --refresh
    python run.py --operator "Voltio" --add-to-universe

The weekly top-10 brief is generated by prompts/run.md from inside Claude Code.
This script exists for ad-hoc one-off operator scoring (e.g. an inbound lead
that needs to be qualified before a meeting).

Requires:
    pip install anthropic pyyaml
    export ANTHROPIC_API_KEY=...
"""

import argparse
import os
import re
import sys
from pathlib import Path

import anthropic
import yaml

# ---------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).parent
UNIVERSE_PATH = PROJECT_ROOT / "data" / "operators.yaml"
SCORING_PATH = PROJECT_ROOT / "scoring.md"
PVP_AGENT_PATH = PROJECT_ROOT / "agents" / "pvp-generator.md"
OUTPUT_DIR = PROJECT_ROOT / "output" / "briefs"

# Sonnet 4.6 is fast enough for single-operator runs. Opus only matters for the
# weekly run where we re-score the entire universe and PVP-generate 10 briefs.
MODEL = "claude-sonnet-4-6"


# ---------------------------------------------------------------------
# Universe handling
# ---------------------------------------------------------------------

def load_universe() -> list[dict]:
    with UNIVERSE_PATH.open() as f:
        return yaml.safe_load(f) or []


def find_operator(universe: list[dict], name: str) -> dict | None:
    """Case-insensitive substring match on operator name."""
    needle = name.lower()
    for op in universe:
        if "name" not in op:
            continue
        if needle in op["name"].lower():
            return op
    return None


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


# ---------------------------------------------------------------------
# Claude orchestration
# ---------------------------------------------------------------------

SYSTEM_PROMPT_PREFIX = """You are Wunder Radar — a multi-agent intelligence \
system for Wunder Mobility's sales team. Your job is to evaluate one \
shared-mobility operator and produce a usable account brief.

Wunder Mobility is a Hamburg-based white-label SaaS platform for shared \
mobility operators (bikesharing, scooter-sharing, moped-sharing, carsharing). \
Customers include Forest (14K e-bikes London), GreenMobility (1,600 EVs \
Nordics), Cooltra, Süwag 2GO, Joco, eddy, Velocity Mobility, CarVia.

You think like a senior B2B SaaS account executive. You score operators on \
Pain × Timing × Wunder Fit. You write briefs that an AE can act on Monday \
morning, not decks. You cite sources for every non-trivial claim.

You have access to web search. Use it to harvest:
  - Recent news (M&A, funding, exec changes, expansion, incidents)
  - Job postings (build-vs-buy signals)
  - App store reviews (platform-blamed pain)
  - LinkedIn posts from leadership (where indexed by Google)

Output a markdown brief in the exact format described below.
"""


def build_system_prompt() -> list[dict]:
    """Build the system prompt with cache breakpoints on the heavy bits.

    Prompt caching saves the universe + scoring rubric + agent definitions
    across calls. These rarely change but are large. Per Anthropic SDK best
    practices the cache survives 5 minutes by default which is plenty for a
    single run.
    """
    universe = UNIVERSE_PATH.read_text()
    scoring = SCORING_PATH.read_text()
    pvp_agent = PVP_AGENT_PATH.read_text()

    # First block: stable preamble + universe (cacheable)
    cached_block = {
        "type": "text",
        "text": (
            SYSTEM_PROMPT_PREFIX
            + "\n\n=== OPERATOR UNIVERSE ===\n"
            + universe
            + "\n\n=== SCORING RUBRIC ===\n"
            + scoring
            + "\n\n=== PVP AGENT SPEC ===\n"
            + pvp_agent
        ),
        "cache_control": {"type": "ephemeral"},
    }

    return [cached_block]


USER_TEMPLATE = """Operator to evaluate: **{operator_name}**

{operator_context}

## Your task

1. Harvest signals across news, jobs, app store reviews, and LinkedIn.
2. Score using the rubric in the system prompt: Pain × Timing × Wunder Fit.
3. Generate a Pain / Value / Proof brief using the PVP agent spec.
4. Pass the 3 WHYs audit on the draft message.
5. Output the full brief as markdown in the format below.

Use the web_search tool liberally. Cite URLs for every signal.

## Output format (Markdown)

```markdown
# {operator_name} — Account brief

**Wunder Radar score:** [X] (Pain [n] × Timing [n] × Fit [n])
**Recommended action:** [one line]
**Generated:** [today's date]

## Snapshot
[table: HQ, geography, fleet, modality, current platform, app rating]

## Why now
[the 1-3 timing signals that matter, with URLs]

## The pain dossier
[the public evidence of pain, with URLs]

## Wunder's specific fit
[capability match, with our proof point]

## Three-message sequence
[message 1: Loom or email to primary contact]
[message 2: follow-up at +7 days]
[message 3: to economic buyer if message 1 engages]

## Discovery questions
[5-7 questions for first call]

## Risks / disqualifiers
[what would kill this]

## Confidence
[High / Medium / Low + reasoning]

## Sources
[bulleted URLs]
```

Begin.
"""


def run_operator_brief(operator_name: str, universe: list[dict]) -> str:
    """Run Claude with web search to produce a brief for one operator.

    Returns the markdown content.
    """
    existing = find_operator(universe, operator_name)

    if existing:
        operator_context = (
            f"This operator is in the tracked universe. Existing record:\n\n"
            f"```yaml\n{yaml.dump(existing)}\n```\n\n"
            f"Refresh the signal harvest. The static record may be stale."
        )
    else:
        operator_context = (
            "This operator is NOT yet in the tracked universe. "
            "Confirm they exist, classify their segment and fleet size, "
            "and produce the brief from scratch."
        )

    client = anthropic.Anthropic()

    # Single-call orchestration. Claude handles tool use loops internally
    # when given the web_search tool.
    response = client.messages.create(
        model=MODEL,
        max_tokens=8192,
        system=build_system_prompt(),
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        messages=[
            {
                "role": "user",
                "content": USER_TEMPLATE.format(
                    operator_name=operator_name,
                    operator_context=operator_context,
                ),
            }
        ],
    )

    # Extract final text. With tool use, the model may have several
    # message turns; the final assistant content block is what we want.
    text_blocks = [
        block.text
        for block in response.content
        if block.type == "text"
    ]
    return "\n\n".join(text_blocks)


# ---------------------------------------------------------------------
# Universe mutation
# ---------------------------------------------------------------------

def add_to_universe(operator_name: str, brief_text: str) -> None:
    """Parse the brief and append a stub record to operators.yaml.

    Conservative: extracts only what's confidently parseable. Anything
    ambiguous is left for the human to fill in.
    """
    stub = {
        "name": operator_name,
        "platform": "Unknown",
        "platform_confidence": "Unknown",
        "status": "Active",
        "wunder_fit": 3,  # provisional, human should refine
        "added_by": "run.py",
        "added_date": "auto",
    }
    universe = load_universe()
    universe.append(stub)
    with UNIVERSE_PATH.open("w") as f:
        yaml.dump(universe, f, sort_keys=False)
    print(f"Stub appended for {operator_name}. Refine wunder_fit manually.")


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Wunder Radar — single-operator runner")
    parser.add_argument("--operator", required=True, help="Operator name to brief")
    parser.add_argument("--refresh", action="store_true", help="Force refresh even if brief exists")
    parser.add_argument("--add-to-universe", action="store_true", help="Append the operator as a stub to operators.yaml")
    args = parser.parse_args()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_path = OUTPUT_DIR / f"{slugify(args.operator)}.md"

    if output_path.exists() and not args.refresh:
        print(f"Brief already exists at {output_path}. Use --refresh to regenerate.")
        sys.exit(0)

    universe = load_universe()
    print(f"Universe loaded: {len(universe)} operators tracked.")
    print(f"Running brief for: {args.operator} (model: {MODEL})")
    print("This typically takes 60-120 seconds with web search...")

    brief = run_operator_brief(args.operator, universe)
    output_path.write_text(brief)
    print(f"\nBrief written: {output_path}")

    if args.add_to_universe:
        add_to_universe(args.operator, brief)


if __name__ == "__main__":
    main()
